### PR TITLE
some changes i made to chilean fascist path for more accuracy

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by SpicyAlfredo — CHANGES_REQUESTED** [review]
I'm fine with everything except the event name change as it's used with the mission for the sae of gameplay consistency. Keep that the same.

**Comment by ghost** [comment]
> I'm fine with everything except the event name change as it's used with the mission for the sae of gameplay consistency. Keep that the same.

ok

**Comment by ghost** [comment]
fixed

**Review by SpicyAlfredo — APPROVED** [review]

**Comment by SpicyAlfredo** [comment]
Thank you

**Comment by ghost** [comment]
> Thank you

no problem :)

**Pull request merged**
