### PR TITLE
Bag of Tricks Feb

### PR DESCRIPTION
**Pull request by SpicyAlfredo**
- Reduce Stat bloat and Vanilla balance adjustments
- Asymmetrical Doctrine more "Vanilla like" in balancing 
- Adjustments and polish in various files

### CODE REVIEW

**Comment by marijn211** [comment]
Error log

**Comment by marijn2112** [comment]
I fixed the Peru war with Ecuador being duplicate, and then the issue with them joining factions started happening, so instead of the AI priorities, there non-intervention ideas are probably not being added

**Comment by marijn2112** [comment]
The victory point defines included now are buggy, I previously had to remove them from PRs by Brit

**Review by marijn211 — CHANGES_REQUESTED** [review]
See above

**Review by marijn211 — APPROVED** [review]

**Review by marijn211 — COMMENTED** [review]
Gibraltar strait is still always friendly

**Pull request merged**
