### PR TITLE
Turkey Partial Rework

### PR DESCRIPTION
**Pull request by BiccyThiccy**
1: Fully reworked Army/Navy/Airforce Tree

2: Slight bug fixes + better AI

3: Some new decisions

Edits in response to feedback:

1: Added fully controls checks to fortification/naval-expansion decisions.

2: Fixed some slight issues

### CODE REVIEW

**Review by ilkober — COMMENTED** [review]
Border fortification decisions should probably check of said states are fully controlled by Turkey - just to make sure you don't give forts to an enemy. Maybe also include a cancel condition where the decision will abort if state gets partially taken? 🤔

**Comment by BiccyThiccy** [comment]
> Border fortification decisions should probably check of said states are fully controlled by Turkey - just to make sure you don't give forts to an enemy. Maybe also include a cancel condition where the decision will abort if state gets partially taken? 🤔

They already do. Look at the decision files, not the focus (the focus does nothing but unlock them)

**Comment by BiccyThiccy** [comment]
I can add checks for the naval expansion focuses though,  in case that was what you were talking about

**Comment by marijn2112** [comment]
Check error log

**Review by marijn211 — DISMISSED** [review]
Check error log

**Comment by BiccyThiccy** [comment]
Errors are fixed, currently working on the remainder of the localization.

**Comment by marijn211** [comment]
I think the army tree might be better with some more extra buildings/free equipment mixed in, some more variety, something like Women in Aviation which you removed

**Comment by BiccyThiccy** [comment]
> I think the army tree might be better with some more extra buildings/free equipment mixed in, some more variety, something like Women in Aviation which you removed

_Women in Aviation_ was replaced with a decision that unlocks after the first army focus.

I can mix in some free equipment effects, three of these focuses after all imply that their army modernization involves increasing arms imports.

Turkey was poor compared to most European countries. I think giving factories for army focuses would make their economy too powerful relative to its historical status. I already think this army rework is a net-buff. I'd be more interested in considering this after I rework the Economy/Industry branch.

I'll make a commit in the next few days, I'll ping you for a re-review when that happens. Thank you.

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
