### PR TITLE
Update philippines.txt

### PR DESCRIPTION
**Pull request by NulledHQ**
This has been bothering me since it needs Manila Central Railway Focus for it be activated
Screenshot 2024-04-26 194239

### CODE REVIEW

**Comment by DutchPlanDerLindeSus** [comment]
No need for this, Philippines has been overhauled so this has been fixed, thx for pointing it out and fixing it tho

**Comment by marijn2112** [comment]
> No need for this, Philippines has been overhauled so this has been fixed, thx for pointing it out and fixing it tho

Has this been pushed or is it on another branch?

**Comment by DutchPlanDerLindeSus** [comment]
> > No need for this, Philippines has been overhauled so this has been fixed, thx for pointing it out and fixing it tho
> 
> Has this been pushed or is it on another branch?

Its Maps March

**Comment by NulledHQ** [comment]
> No need for this, Philippines has been overhauled so this has been fixed, thx for pointing it out and fixing it tho

oh really can't wait then

**Pull request closed without merging**
