### PR TITLE
Locale update for USA and Sweden

### PR DESCRIPTION
**Pull request by theodorhansson**
This PR changes or adds the following:
* Changes default text for Fighter-Bombers.
* Adds Swedish ship class names.
* Adds Swedish modern tank names, with flavor text.
* Updates American plane names.
* Fixes bug with american torpedo bomber locale missing.
* Adds missing American ship class names.
* Some minor cleanup in locale files, wrong location or weird item order.

The locale has been tested on my machine and looks good.

### CODE REVIEW

**Review by SwedishNorwegian — CHANGES_REQUESTED** [review]
The Swedish names, especially for the ship classes, make no sense. Sweden may be a Scandinavian country, but that does not mean that every ship class above a Cruiser would be Norse themed. 

Remove The Battleship, Carrier, Battlecruiser. Super Heavy Battleship names.

Also go through and remove any meme that you've put in, whether it is in Swedish localization or in the American localization.

When it comes to tanks, if you want those included, use the Strv 103 instead of the Centurion based hulls for as long as possible, ie; after Modern Tank 1. Better to use domestic designs instead of foreign.

**Comment by theodorhansson** [comment]
I have now removed all references to norse gods. I have also removed the memes I added.

Regarding the Strv 81 (Centurion). It has been in the Swedish tech tree since 2021 when Abbus added it in commit 5484d3d63d73203a408dc39fbf88b9f61541adac. What I have done is add its later variants along with the completely different Strv 103. The problem with using the Strv 103 is that it arrives relativly late. It first first saw service in 1966 with later variants arriving in 1970.

**Comment by TheBrit7** [comment]
Any references to memes will not be accepted.

**Comment by theodorhansson** [comment]
@TheBrit7 As per my last comment, memes have been removed in commits 93f18ed299d0bf41513876c3b16f0671b13a8466 and 8bd3884bebf81dbed6eb386c514af7bbda3357ad.

**Comment by theodorhansson** [comment]
New changes:
* Added Swedish namelists for ships (Kings, Provinces, Birds and Fish).
* Made Swedish ship names more historical. Now more focused on regions than royalty and gods.
* ~~Fixed weird formatting error (fixed by a complete rebase). Maybe caused by missing EFBBBF byte order mark?~~ Old commit history has been restored.
* Strv 103 now more prominent in tech tree.
* Changed Swedish heavy and superheavy tank names to "Tung" and "Övertung" respectively.
* Added generic Swedish light tank names. Ex. "Lätt stridsvagn m/45 (L Strv)" = "Light tank m45".

**Review by ilkober — COMMENTED** [review]
It has still that Harambe description in it

**Comment by theodorhansson** [comment]
@ilkober It has the what now?
Edit: It was a meme that already existed in the game files

**Comment by theodorhansson** [comment]
Harambe and other pre-existing sillyness has been removed.

**Review by marijn211 — COMMENTED** [review]
Some of the loc changes look nice, but I dont know if the Sweden changes make any sense

**Comment by marijn211** [comment]
I'm gonna assume some Sweden names were still considered to be questionable and close this, I'm neutral to the other changes so maybe discuss on the Discord if you wanna bundle those with something else or adjust it

**Pull request closed without merging**
