### PR TITLE
Pepper peru 5

### PR DESCRIPTION
**Pull request by pepper419**
-new mechanic gui for peru

-new bop for peru

-new economic tree for peru

-secret way oil republic for peru 

-new inka reich secret tree

- new fascist way and commie things

- new rey of peru way

### CODE REVIEW

**Review by marijn211 — CHANGES_REQUESTED** [review]
Previous feedback has _still_ not been addressed, this is the third or fourth time asking for the fixing of the error log and removal of combat stats from the BoP

**Review by marijn211 — CHANGES_REQUESTED** [review]
Same issues as before

**Comment by marijn211** [comment]
Can confirm there are still errors that need resolving

**Review by marijn211 — CHANGES_REQUESTED** [review]
Pepper for the love of god stop cramming in more and more content and fix the errors so the branch can be accepted

**Comment by pepper419** [comment]
> Pepper for the love of god stop cramming in more and more content and fix the errors so the branch can be accepted

I was checking the error log and also possible bugs in the game and I didn't find anything, I also fixed the bop and it no longer gives war bonuses

**Comment by marijn211** [comment]
> > Pepper for the love of god stop cramming in more and more content and fix the errors so the branch can be accepted
> 
> I was checking the error log and also possible bugs in the game and I didn't find anything, I also fixed the bop and it no longer gives war bonuses

When I checked there were still errors about invalid effects on launch
For checks this month Im unavailable but you could ask someone else

**Comment by marijn211** [comment]
Remaining errors might be with/without certain DLC only, marking as normal PR but still wait for after update to check and accept ofc

**Review by marijn211 — DISMISSED** [review]
Checked most files, please:
- [ ] Make sure PRU_hit_chile works now the Monroe doctrine was changed
- [x] Rename Unite_the_High_Command formable decision ID to not have capitals and be so generic and fix identation in its file
- [x] Remove as much as possible the seemingly random capitalization of focus IDs, alongside the dreadful indentation

**Review by marijn211 — DISMISSED** [review]
Theres error log from inconsistently removing capital letters from focus names, ideally they should be removed from every focus

**Review by marijn211 — CHANGES_REQUESTED** [review]
The BoP GFX seems broken, and some GUI system decisions dont show an effect

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
