### PR TITLE
Pepper peru

### PR DESCRIPTION
**Pull request by marijn211**
No errors - English looks good

Should be able to merge with not too many changes, just do some playtesting and balance checks

### CODE REVIEW

**Review by SpicyAlfredo — COMMENTED** [review]
Needs more polish. Merge after update - SpicyAlfredo

**Comment by SpicyAlfredo** [comment]
Also resolve idea file conflict please before next checkup

**Comment by SpicyAlfredo** [comment]
I'm just going to merge this after the 7th, Ready or Not

**Comment by SpicyAlfredo** [comment]
Merge beta edits into the pull. This baby bird needs to learn to fly

**Review by TheBrit7 — APPROVED** [review]
Interesting analogy, Logan.

**Pull request merged**
