### PR TITLE
Austria Rework by RobloxFanboy86

### PR DESCRIPTION
**Pull request by hammmurabi**
the time has come to say goodbye to the worst focus tree in the mod.

I present to you, full Austria rework with 9 potential leaders and 11 political paths.

### CODE REVIEW

**Comment by hammmurabi** [comment]
Marking PR as open, still a couple small things missing but is ready for beta (needs GFX and a bit more ai modding)

**Review by marijn211 — COMMENTED** [review]
available statement of ``AUS_federalize_transleithania`` doesnt make sense, Hungary cant have puppets AND not exist

**Review by marijn211 — CHANGES_REQUESTED** [review]
Merge conflicts in r56_traits, trait ``jumping_general`` for example was fixed a while ago and is broken again on this branch

**Review by marijn211 — COMMENTED** [review]
The industrial fund thing in the industry tree seems completely unnecessary, as its quite cheap and has no difficulty, it doesnt really add gameplay value

**Review by marijn211 — COMMENTED** [review]
An Austrian civil war seems to fire too easily, and it wasnt clear enough to me that it was about to happen

**Comment by hammmurabi** [comment]
> An Austrian civil war seems to fire too easily, and it wasnt clear enough to me that it was about to happen

please put your comments in the discord channel so its easier to reply to them 

as for this one the decision category clearly tells you when the civil war will fire

**Review by marijn211 — APPROVED** [review]
Gonna try to fix 2 minor bugs, then merge

**Pull request merged**
