### PR TITLE
Lithuania Mission Fix

### PR DESCRIPTION
**Pull request by lolman-warrior**

### CODE REVIEW

**Review by Thinking-waffle — CHANGES_REQUESTED** [review]
How is LIT_cadets_return_from_abroad_mission supposed to work if it's available when LIT doesn't exist and at the same time requires you to be Lithuania so which is it?

**Comment by lolman-warrior** [comment]
It a mission, available "completes" the mission, and since the rewards are granted to the player through timeout of mission, completing the mission would equivalent to a fail, hence the change

**Comment by lolman-warrior** [comment]
I am sorry for the weird explanation but it works perfectly with the adjustment, trust me, I've tested it and modeled after "Save Alcazar" Spanish Mission

**Comment by Thinking-waffle** [comment]
I forgot how missions work. And honestly, they work in a very strange way.

**Review by Thinking-waffle — APPROVED** [review]

**Pull request merged**
