### PR TITLE
Uzbekistan: Characters

### PR DESCRIPTION
**Pull request by SanzhKM**
Wouldn't hurt...

### CODE REVIEW

**Comment by ilkober** [comment]
Characters have no assignment to a country
And they don't have names defining their strings
Plus, leaders have no portraits defined (even generic ones)

**Comment by SanzhKM** [comment]
> Characters have no assignment to a country And they don't have names defining their strings Plus, leaders have no portraits defined (even generic ones)

I mean uzbekistan has no advisors, high, command or generals so ya'll could pick out those you wanna keep, sort of like "assigning" them or recruiting them through _recruit_character.

also tf you mean by "names defining their strings"?

**Comment by ilkober** [comment]
> I mean uzbekistan has no advisors, high, command or generals so ya'll could pick out those you wanna keep, sort of like "assigning" them or recruiting them through _recruit_character.

Since there is no info on them provided, they could be randoms which we will have to check twice instead. And since the translation of poitentially cyrillic alphabet doesn't go smoothly, having additional info would be great. Who are they, background etc. Check some of the other advisors we have, for example like I did in Mongolian file.

> also tf you mean by "names defining their strings"?

Advisors have an entry which is aimed to give them specific names like 
SOV_iosof_stalin = {
      name = "Iosif Stalin"
      ...
}
Otherwise the game will likely either display a broken SOV_iosif_stalin string OR will assign the generic name

**Comment by SanzhKM** [comment]
> 

Get ready for round 2

**Pull request closed without merging**
