### PR TITLE
Quebec bugfixes & Advisors

### PR DESCRIPTION
**Pull request by LauraPoggies**

### CODE REVIEW

**Review by ilkober — COMMENTED** [review]
Mentioned issues are to found in Laura's channel

**Comment by LauraPoggies** [comment]
That should be all the issues, hopefully.

**Comment by marijn211** [comment]
In what contexts do the accented VP and state names cause issues?

**Review by marijn211 — DISMISSED** [review]

**Comment by marijn211** [comment]
[23:29:57][no_game_date][effectimplementation.cpp:2152]: common/national_focus/quebec.txt:7301: swap_ideas: Invalid idea: QBC_quebecois_socialist_agrarianism. If you wanted to reference a variable, you need to explicitly prefix it with var: or temp_var:.
[23:29:57][no_game_date][effectimplementation.cpp:2152]: common/national_focus/quebec.txt:7370: swap_ideas: Invalid idea: QBC_quebecois_socialist_agrarianism. If you wanted to reference a variable, you need to explicitly prefix it with var: or temp_var:.
[23:30:02][no_game_date][lexer.cpp:213]: Tried to get dynamic token that does not exist: civilian_cost_factor

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
