### PR TITLE
Achievements and Ribbions

### PR DESCRIPTION
**Pull request by SpicyAlfredo**

### CODE REVIEW

**Comment by SpicyAlfredo** [comment]
Waiting on icons

**Comment by marijn211** [comment]
You could comment out the start_date_checks in the ribbons

**Comment by marijn211** [comment]
Also lategame techs and late doctrines are basically just lame af waiting achievements

**Comment by SpicyAlfredo** [comment]
> Also lategame techs and late doctrines are basically just lame af waiting achievements

That's the point of the ribbons, they're just passive feel good pop-ups. Not things you aim for or center a playthrough around.

**Pull request closed without merging**
