### PR TITLE
Portrait reorg

### PR DESCRIPTION
**Pull request by PordyHUN**
All the leader portrait purged from black&white pictures, Very low quality colored pictures.
All leader portrait picuture get thier own r56_portrait_HUN_ foretag, and every code follows it.

Warning:
Because of the numerous cross-references, this could pull could have a load of erros, what really hard to check, because some leaders came from decisions or events, and without firing them, they doesnt appear.
I am apologize, but bugfixing maybe lasts much longer.

I am working with the artist, to replace the bad quality colored pictures,

Note:
Belgian VLA and WLL icons are untuched, because i have to implement a new BEL mod, so i dont want to do a double-work.

### CODE REVIEW

**Comment by Greatexperiment** [comment]
[09:44:58][effect.cpp:215]: Error: "Unexpected token: portrait_path, near line: 125
" in file: "history/countries/BRA - Brazil.txt" near line: 132
[09:44:58][effect.cpp:215]: Error: "Unexpected token: .dds, near line: 120
Unexpected token: 1965.1.1, near line: 145
Unexpected token: 1936.1.10, near line: 151
Unexpected token: Federico, near line: 151
Unexpected token: Brú, near line: 152
Unexpected token: POLITICS_FEDERICO_LAREDO_BRU_DESC, near line: 153
Unexpected token: gfx/leaders/South, near line: 153
Unexpected token: 

		expire = , near line: 154
Unexpected token: 

		ideology = socialism

		traits = {

			#

		}

	}

}

create_field_marshal = {

	name = , near line: 162
Unexpected token: Perez, near line: 162
Unexpected token: 

	portrait_path = , near line: 163
Unexpected token: America/Portrait_South_America_Generic_land_2.dds, near line: 170
" in file: "history/countries/CUB - Cuba.txt" near line: 170
[09:44:58][effect.cpp:215]: Error: "Unexpected token: portrait_path, near line: 138
" in file: "history/countries/LIT - Lithuania.txt" near line: 144
[09:44:59][effect.cpp:215]: Error: "Unexpected token: portrait_path, near line: 3508
" in file: "events/CNF_commies.txt" near line: 3514

**Comment by Greatexperiment** [comment]
There are also a couple of file conflicts here that should be resolved - listed above.

**Comment by PordyHUN** [comment]
Conflicts resolved, error log cleared, ready to rewiev.

**Comment by Greatexperiment** [comment]
Initial log is clear.

**Pull request merged**
