### PR TITLE
Sweden Rework PR

### PR DESCRIPTION
**Pull request by SwedishNorwegian**
This should be ready for PR. 
Note: I am waiting on a new portrait and focus icon for Gösta Bagge. Using temporary icon/portrait for him at the moment.

### CODE REVIEW

**Review by ilkober — DISMISSED** [review]
Descriptor file needs to be changed back

**Review by ilkober — COMMENTED** [review]
Looks good.
If @SpicyAlfredo or @Thinking-waffle could check once to be sure, would be great.

Otherwise can be approved on the fast glance.

**Review by SpicyAlfredo — APPROVED** [review]
Passes the eye test

**Review by TheBrit7 — APPROVED** [review]
Looks good.

**Review by marijn211 — APPROVED** [review]
No error log on launch/load; focus tree, early events and some decisions I checked in-game were all good

**Pull request merged**
