### PR TITLE
Egypt AI improvements and technology fixes

### PR DESCRIPTION
**Pull request by TheBrit7**

### CODE REVIEW

**Review by SpicyAlfredo — CHANGES_REQUESTED** [review]
Moving the RK states of the Goverment government to Ukraine was not the change I was okay with. It needs a new decision to expand the General Government to these new states or leave it as is.

**Comment by SpicyAlfredo** [comment]
Everything else looks good

**Comment by TheBrit7** [comment]
No, because otherwise Generalgovernment wont exist by the time they should, which overall makes them quite redundant. I also recall you saying that I was free to change it as I wish so with such a minor change I far from seeing it matter.

**Comment by TheBrit7** [comment]
Your requested changes should be addressed. Please remove your block.

**Review by ilkober — CHANGES_REQUESTED** [review]
MON_states_required_for_greater_mongolia_flag in on_actions 
is no longer needed since formables have been reworked and the flag is obsolete

**Comment by TheBrit7** [comment]
Done

**Pull request closed without merging**
