### PR TITLE
national character changes

### PR DESCRIPTION
**Pull request by ItsFlor**
for national characters:
- tooltip aligning
- reordering to make more sense
- minor balance changes (pls check these!!!):

cultural norms:
industrial_capacity_factory = 0.05

revolutionary minds
nuclear_production_factor = 0.10
industrial_capacity_factory = -0.10

cultural norms:
stability_factor = 0.05 -> stability_factor = 0.10

melting pot:
starting_compliance = 0.10

### CODE REVIEW

**Review by ilkober — DISMISSED** [review]
```order_above_all_tt:0 "\nAvailable to the following governments:\n§2Populism\nOligarchic Democracy§!\n§RLeninism\nStalinism\nAnti-Revisionism\nIslamic Socialism\nJuche\nArab Communism\nNational Bolshevism§!\n§ONational Socialism\nFascism\nFalangism\nUltranationalism\nClerical Fascism\nRexism\nRight Marhaenism\nIslamism§!\n§gDespotism\nAbsolute Monarchism\nOligarchism\nCorporatism\nPeople's Tutelage\nTheocratic Monarchy\nIslamic Nationalism\nMilitary Junta\nMarhaenism\nArab Socialism\nRevisionist Zionism\nColonial Government\nPashtun Nationalism§!\n"```

**Comment by marijn211** [comment]
Its kinda confusing to check the difference when you seemingly swapped around the order of some laws in the file

**Comment by marijn211** [comment]
1% conscription on greater good is as much as going from limited to extensive conscription, would not change that stat, I think its already viable when you wanna build forts and/or need manpower as someone stuck on low mob

IIRC cultural norms used to buff factory output instead of the stability, maybe you could restore that instead but do like 5% or less, keep in mind that stat raises 10% every industrial technology tier, so it isn't as much as it sounds like

**Review by marijn211 — CHANGES_REQUESTED** [review]
Above

**Pull request closed without merging**
