### PR TITLE
East Indies Reworked (part 1)

### PR DESCRIPTION
**Pull request by KrasnaMerah**
Adding character names, two new nation tags, several new companies and MIOs, and several leader and advisor portraits.

### CODE REVIEW

**Comment by marijn211** [comment]
To confirm since its marked part 1 and tagged on-going, is it ready to be checked?

**Comment by KrasnaMerah** [comment]
Oh yeah, please review it, everyone.

**Comment by marijn211** [comment]
Some of the portraits seem to be of lower quality

**Review by marijn211 — COMMENTED** [review]
It seems you have different spellings of INS_urip_sumoharjo in the character file compared to the focus tree? Unless they are different people, I just noticed the removed GFX file of a Sumoharjo

**Review by marijn211 — COMMENTED** [review]
[01:43:14][no_game_date][ai_strategy.cpp:162]: in file common/ai_strategy_plans/INS_alternate_strategy_plan.txt line: 172
[01:43:14][no_game_date][ai_strategy.cpp:165]: invalid focus for ai strategy INS_indigenous_voices
[01:43:16][no_game_date][triggerimplementation.cpp:3307]: Invalid focus scripted in trigger. has_completed_focus = INS_commit_hakko_ichiu (common/ideas/indonesia.txt:1266: has_completed_focus)
[01:43:16][no_game_date][trigger.cpp:114]: Trigger failed to validate: common/ideas/indonesia.txt:1266: has_completed_focus
[01:43:16][no_game_date][triggerimplementation.cpp:3307]: Invalid focus scripted in trigger. has_completed_focus = INJ_invite_zaibatsus (common/ideas/indonesia.txt:1267: has_completed_focus)
[01:43:16][no_game_date][trigger.cpp:114]: Trigger failed to validate: common/ideas/indonesia.txt:1267: has_completed_focus
[01:43:16][no_game_date][triggerimplementation.cpp:3307]: Invalid focus scripted in trigger. has_completed_focus = INS_make_use_nsboi (common/characters/INS.txt:318: has_completed_focus)
[01:43:16][no_game_date][trigger.cpp:114]: Trigger failed to validate: common/characters/INS.txt:318: has_completed_focus
[01:50:39][1936.01.01.12][effectimplementation.cpp:5289]: history/countries/INS - Indonesia.txt:92: recruit_character: Unknown character INS_amir_sjarifuddin_harahap
[01:50:39][1936.01.01.12][effectimplementation.cpp:1868]: history/countries/PPA - Papua.txt:46: add_ideas: Invalid idea: ASEAN_agrarian_society_1. If you wanted to reference a variable, you need to explicitly prefix it with var: or temp_var:.

**Review by marijn211 — CHANGES_REQUESTED** [review]
Above

**Comment by KrasnaMerah** [comment]
Okay, got them fixed and updated. Mostly just focus requirements, but i've added Huib van Mook there along with advisor roles for Musso Munawar and Kartosuwiryo

**Review by marijn211 — APPROVED** [review]
Gonna look through some stuff then accept unless I find some major problem

**Review by marijn211 — DISMISSED** [review]
Lots of broken advisor/company pictures, missing loc on MIOs, no navy/airforce chiefs?

**Comment by KrasnaMerah** [comment]
Standarize idea portraits and idea naming on interface file, filling the missing portraits interface naming, adding Zentgraff and naval chiefs, and syncing the pull with updated Beta Branch

**Comment by KrasnaMerah** [comment]
Adding Maarten van Dulm as Navy Chief (i forgot him)

**Comment by marijn211** [comment]
[11:31:21][no_game_date][triggerimplementation.cpp:3307]: Invalid focus scripted in trigger. has_completed_focus = INS_air_offense (common/characters/INS.txt:889: has_completed_focus)
[11:31:21][no_game_date][trigger.cpp:114]: Trigger failed to validate: common/characters/INS.txt:889: has_completed_focus
[11:31:21][no_game_date][triggerimplementation.cpp:3307]: Invalid focus scripted in trigger. has_completed_focus = INS_air_defense (common/characters/INS.txt:890: has_completed_focus)
[11:31:21][no_game_date][trigger.cpp:114]: Trigger failed to validate: common/characters/INS.txt:890: has_completed_focus
[11:31:21][no_game_date][triggerimplementation.cpp:3307]: Invalid focus scripted in trigger. has_completed_focus = INS_air_offense (common/characters/INS.txt:922: has_completed_focus)
[11:31:21][no_game_date][trigger.cpp:114]: Trigger failed to validate: common/characters/INS.txt:922: has_completed_focus
[11:31:21][no_game_date][triggerimplementation.cpp:3307]: Invalid focus scripted in trigger. has_completed_focus = INS_air_defense (common/characters/INS.txt:923: has_completed_focus)
[11:31:21][no_game_date][trigger.cpp:114]: Trigger failed to validate: common/characters/INS.txt:923: has_completed_focus



"gfx/interface/ideas/ins/advisors/r56_idea_INS_advisor_syahrir.dds"
seems to be missing

**Comment by KrasnaMerah** [comment]
> seems to be missing

Done

In addition of your suggestions, i'm also adding Hamengkubuwono IX's "Army" portrait and he becomes a Field Marshal when he gets to become a leader through the 'fascist' path

**Review by hammmurabi — CHANGES_REQUESTED** [review]
lots of broken localization and low quality portraits (fascist leader for example), cannot be merged at this time

**Review by hammmurabi — APPROVED** [review]
some GFX really needs to be redone, but since this has been open so long im accepting

**Pull request merged**
