### PR TITLE
Waffle may 1

### PR DESCRIPTION
**Pull request by Thinking-waffle**
important:  

- test if the new mongol, tuvan infantry using PRC models with soviet rifles and smgs work.
- test PER tanks (for now without NSB) (it should be CZE tanks except early light tanks with a Czech made Romanian tankette)

### CODE REVIEW

**Review by marijn211 — DISMISSED** [review]
SWI file is incorrectly instanced, Ill fix that at some point

**Comment by marijn211** [comment]
Error log free on launch, so the models spoken off can't be too broken

**Comment by ilkober** [comment]
There are currently 15 conflicting files...

**Comment by Thinking-waffle** [comment]
oh boy I probably won't be able to fix such a merge today.

**Review by marijn211 — DISMISSED** [review]
Doing final checks rn

**Review by marijn211 — CHANGES_REQUESTED** [review]
Crashes for unknown reason after merge, am checking

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
