### PR TITLE
Waffle february 2

### PR DESCRIPTION
**Pull request by Thinking-waffle**
This adds a secret focus to unlock a special operation to get the Stone of Scone back with agents. It is necessary to test it.
To unlock it the English must refuse and then instead of getting a wargoal if you have the dlc you can focus on spies instead and gain a secret focus.

### CODE REVIEW

**Comment by marijn211** [comment]
It doesnt make sense that free trade has a smaller buff than export focus, it exports more resources
Also, it seems more sensible to put such buffs onto the conscription laws, as otherwise countries with no resources to export get even more buffs for free.

**Review by marijn211 — DISMISSED** [review]
[00:24:17][no_game_date][operationphase.cpp:66]: Operation phases references a phase that does not exist: targeted_take_the_stone_of_scone

**Comment by Thinking-waffle** [comment]
I see what I missed, I could have variety but that's enough for now.

It should be fixed (I changed the text too as it was incorrectly set up with the description used as the title)

**Comment by marijn211** [comment]
Ill took a look at the vanilla balance changes you ported and accept if those seem right

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
