### PR TITLE
Coat of pain(t) for Philippines

### PR DESCRIPTION
**Pull request by Thinking-waffle**

### CODE REVIEW

**Comment by marijn2112** [comment]
[01:14:53][pdxmeshtype.cpp:152]: Could not find mesh file gfx/models/units/planes/ITA_carrier_nav_3.mesh for generic_ITA_carrier_nav_3_mesh, switching to gfx/models/test_object.mesh
[01:14:53][pdx_anim.cpp:1125]: Animation [fighter_default_idle_animation]: Animation's number of joints does not match mesh's number of joints. ( Animation 1, Mesh 2)
[01:14:53][pdxmeshtype.cpp:324]: Animation [fighter_default_idle_animation] is not compatible with mesh [generic_ITA_carrier_nav_3_mesh]

**Review by marijn211 — APPROVED** [review]
Adds error log when BBA isnt enabled, but seems fine otherwise

**Review by marijn211 — CHANGES_REQUESTED** [review]
On further inspection, it seems that the diff contains file changes that revert previous commits to the main (noticed on the gamerules file, but there might be more unintended changes)

**Comment by marijn211** [comment]
Reverted presumed unintended changes to the gamerule file, except the removal of a recently added DLC check on the South African AI gamerule which is also checked for the Road to 56 tree, so I removed that check again

**Review by marijn211 — APPROVED** [review]

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
