### PR TITLE
Some Tweaks

### PR DESCRIPTION
**Pull request by Rokim21**
Generals can now lead 30 divisions, Field Marshals can lead 100 and army,navy and airforce experience is capped at 1000.

### CODE REVIEW

**Comment by Greatexperiment** [comment]
Why is this needed?

**Comment by Rokim21** [comment]
Why not?

**Comment by Greatexperiment** [comment]
If there's a case to be made, sure. It needs to improve gameplay, or be a much requested feature.

**Comment by Rokim21** [comment]
It improves gameplay, it's too easy to get at 500 xp which makes upgrading equipments kinda shitty, also a 30 divisions general is much better for small nations, and a 100 divisions field marshal makes sense and it's useful for massive countries like the Soviet Union and the German Reich.

**Comment by Greatexperiment** [comment]
The xp cap increase is fine. Not going to mess with the general / marshall caps though.

**Comment by Rokim21** [comment]
Then that way it will be!

**Pull request merged**
