### PR TITLE
Waffle april 1

### PR DESCRIPTION
**Pull request by Thinking-waffle**
Beware of the Catalinas (and mostly their predecessors) in the USA history file.

Vasyl Ukraine should get +1000 opinion with Habsburg Poland and Otto's AH

### CODE REVIEW

**Review by marijn211 — CHANGES_REQUESTED** [review]
Plane icon file has a lot of (new) wrong scope errors
I wouldn't know for sure but it looks like all the cosmetic-tag based icons do not work like that

**Comment by TheBrit7** [comment]
This PR has a lot of errors.

**Review by marijn211 — APPROVED** [review]
Despite spamming errors, the cosmetic tag specific plane models do seem to work perfectly fine

**Comment by Thinking-waffle** [comment]
But the SPA_director_fighter and poum_fighter things need to be fixed.

**Pull request merged**
