### PR TITLE
Science Boom! New italy tree, Modified ETAX tree, man the guns compatibility fixes! Whales and Unicorns!

### PR DESCRIPTION
**Pull request by PordyHUN**
1. +1 research slot for every country. Nor the AI nor the players could keep up techs up to date nearly, because of the new technologies. It wont makes any country OP.
2. Ahead time penalty was doubled to prevent players in multiplayer match for rushing some tech.
3. Lowered the spotting chance of the army transport convoys. This result that the AI wont loose all of thier troops against the first boat with a rifle on the board.
4. Trying to fight against the italian AI behaviour, that they immediately abandon the somaliland and bring back their troops to Italy. I added a port to north east somaliland to give chance the AI to land their reinforcement before Ethiopians overrun it, i altered the italian OOB and moved some armored divisions from italy to somaliland. In numerous cases this will prevent the AI from pulling thier troops out, and empty the southern front.
5. Teached the AI to research in the etax techtree like as the land doctrines. So you wont overpower the AI because the army focus tree! Army focus for every country, the ai will focus these doctrines more when are at war. 
Army Focus: Firepower branch: GER SOV USA Defense branch: ITA FRA JAP ENG
Air focus Firepower branch: ENG Defense Branch GER
Navy focus Firepower branch USA Defense branch: ITA JAP FRA
The Ends for GER ITA SOV JAP Glory branch for JAP GER Desperation branch for ITA SOV.
The means Unity branch for FRA ENG Business branch USA and minors in generic.
Practical branch GER ITA FRA, Grand Project branch USA ENG SOV
Great Works GER JAP Quality ENG FRA The Bomb USA, Super soldiers JAP SOV
This way ENG GER JAP USA can max out thier potential, SOV FRA ITA cant research the last doctrine.
6. Etax army focus doesnt give you Armor organization! No more pure armor divisions!
7. Fixed Polish Moscicky portrait finally.
8. Brand new Italy focus tree for fascist branch. (The focus tree based on Total War's italy focus tree. ) The tree isnt complete yet, open for testing.
9. Added Marno's ENG focus icons.
10. Makeshift fix on soviet baltic claims branch bypass issues.
11. Removed a lot of TGA graphics file and replaced with .dds version (Thx abbus!)
12. Altered some defines for a better game experience.
- Disbanding encircled units only returns 10% manpower and equipment.
- Disbanding a division in home territory will return 100% manpower.
- Lowered base tech cost from 85 to 80 day.
- Increased the year ahead penalty from 2 to 6.
- Increased the savable days on research to 50 from 30
- Slower mission efficiency gain for bombers
- Lowered the air supply mission command point cost.
- Default occupation policy set to gentlest
- Lowered naval mines naval supremacy impact to 0.75 from 1.0,
- Slightly lowered naval mines damage

### CODE REVIEW

**Comment by Greatexperiment** [comment]
Conflicts with a Waffle pull. Same comment as I mentioned previously: The two of you need to coordinate. Most every pull you guys are submitting conflicts with the other.

**Comment by PordyHUN** [comment]
Conflict resolved.

**Comment by PordyHUN** [comment]
Closing for testing.

**Comment by Greatexperiment** [comment]
Update the notes as per usual.

**Pull request merged**
