### PR TITLE
 Infantry equipment for Luxembourg

### PR DESCRIPTION
**Pull request by halcyon-gh**
A few suggestions for Luxembourgian infantry equipment, mainly to allow neighbors to capture named equipment. Since I found no information on weapons used by the corps of volunteers before 1940, the list is based on weapons used in the reformed army in 1945, listed on the (archived version of the) website of the Luxembourg National Museum of Military History.

https://web.archive.org/web/20121002013357/http://www.mnhm.lu/pageshtml/virtualmuseumtour.php#partb

### CODE REVIEW

**Comment by halcyon-gh** [comment]
It seems that I'm not really following correct procedures. Sorry about that. I was going through some files to check language, and that was not supposed to end up here yet. Still trying to get familiar with the github thing. I've now made a new branch of my fork to work on, so things should be kept separate (I hope).

**Comment by SpicyAlfredo** [comment]
Is this branch ready to merge or are you still working on changes?

**Comment by SpicyAlfredo** [comment]
You might not know how Github works, but these are good changes even if they're by accident haha. So I'm going to merge. Thank you for your work.

**Comment by halcyon-gh** [comment]
Thanks. It was the plan to try the small Luxembourg update to figure out how it works. I'm now going through the whole Belgium file to fix the spelling and such. This might take a couple of weeks though. Really like your mod, so happy to contribute a bit.

**Pull request merged**
