### PR TITLE
Fovarstaaben

### PR DESCRIPTION
**Pull request by TheCrazyAnarchist**
Forvarstaaben focus goal, nothing to see here!

### CODE REVIEW

**Comment by ilkober** [comment]
Maybe also define it in gfx\interface\goals\swe?

**Comment by TheCrazyAnarchist** [comment]
will do.

**Review by TheBrit7 — CHANGES_REQUESTED** [review]
Please keep the file name consistent with the naming scheme for focuses.

Also, is this defined in the r56_goals.gfx and r56_goals_shine.gfx? Otherwise it wont work at all.

**Comment by TheBrit7** [comment]
Closing due to changes not being made.

**Pull request closed without merging**
