### PR TITLE
Honduras National Focus Changes

### PR DESCRIPTION
**Pull request by Zurich899**
Various fixes, improvements, and nerfs to Honduras's national focus (there will be some events and decision changes later)

### CODE REVIEW

**Comment by Greatexperiment** [comment]
I will review these on Monday.

**Comment by Greatexperiment** [comment]
Clear - Also be sure to add your changes to the wiki.

**Comment by Greatexperiment** [comment]
Be sure to add your other changes to the wiki notes if you haven't already.

**Comment by Zurich899** [comment]
Thank you. Although I haven't used the Wiki before, and I just finished looking over the Patch Notes area. Do I need permission to edit the patch notes, or am I blind and missing the edit button?

**Pull request merged**
