### PR TITLE
Manchuria

### PR DESCRIPTION
**Pull request by RMD-Angel**

### CODE REVIEW

**Comment by Thinking-waffle** [comment]
Need fixes regarding the multiple Pu Yi Characters

**Review by Thinking-waffle — CHANGES_REQUESTED** [review]
There are multiple versions of Pu Yi while all of them should logically be under the same character (although 2 versions may exist to fit the different trees)

**Comment by SpicyAlfredo** [comment]
Waffle is this branch good now?

**Comment by Thinking-waffle** [comment]
Problems are still there I described them in devchat.

**Review by Thinking-waffle — APPROVED** [review]

**Pull request merged**
