### PR TITLE
Typos and correct hyphenation 

### PR DESCRIPTION
**Pull request by tobiasjcat**
### Summary
Here are more small changes to the `localisation/english/` files. I did my best to preserve the intended wording instead of rewording whole sentences.  
I was careful to not modify anything, even casing, on the left side of a `:0` in a line.

### Examples
The checked boxes are changes I made. Unchecked means I avoided those changes.   
- [x] Single word corrections
- - [x] `Pratice` -> `Practice`
- - [x] `maintainance`-> `maintenance`
- - [x] `acheive` -> `achieve`
- [x] Simple rewording
- - [x] `arouse` -> `has arisen` 
- - [x] `officialize` -> `officially declared`
- [ ] Americani**zation** vs Britishi**sation** (something on my docket)
- - [ ] `organisation` -> `organization`
- [x] Hyphenation
- - [x] `aircrew` -> `air-crew`
- - [x] `warmup` -> `warm-up`
- [ ] Variable names
- - [x] `[HOl.getADJective]` -> `[HOL.GetAdjective]`  (casing only)
- - [ ] `USA_develop_carribean:0 "Develop The Carribean"` -> `USA_develop_caribbean:0 "Develop The Caribbean"` (did not correct misspellings before `:0`)
- - [x] `USA_develop_carribean:0 "Develop The Carribean"` -> `USA_develop_carribean:0 "Develop The Caribbean"` (only after `:0`)
- [ ] Grammatical corrections of correctly spelled word (Another task for a later MR)
- - [ ] `who` -> `whom`
- - [ ] `less enemy divisions` -> `fewer enemy divisions`

### CODE REVIEW

**Comment by marijn211** [comment]
Most of the hyphen introductions I have doubts about, other than that seems good

**Comment by tobiasjcat** [comment]
Reviewing it again and checking against wiktionary, I see I made some errors. I'll have another commit soon.

**Comment by tobiasjcat** [comment]
Checking wiktionary proved me wrong in a lot of cases of hyphens. In the future I'll make sure to give it another pass. I've also updated the dictionary I've been using to find misspellings with these corrected spellings.

Didn't require hyphen:
- steelmaking
- multiethnic
- roadwheels
- jettisonable
- citystate
- counterstrike
- strikeforce
- counterblow
- woolwashing
- counterpurge
- wardlordism
- footsoldiers

Required a space:
- [Home Guard](https://en.wikipedia.org/wiki/Croatian_Home_Guard_(World_War_II))

Did require hyphen:
- must-have
- ever-seeking  

Hyphens I missed:
- non-oppressive

**Comment by marijn211** [comment]
Aside from "citystate" everything seems correct, I can't find that word with that spelling, mostly spelled as "city-state"
I'd have corrected this myself and merged, but its a fork so itd be rather inconvenient, ready other than that

**Comment by marijn211** [comment]
If you update the fork so it doesnt have any commits its behind on, itll be all ready

**Review by marijn211 — APPROVED** [review]

**Comment by tobiasjcat** [comment]
Thanks for your help. I'll work off branches instead of a fork going forward.

**Pull request merged**
