### PR TITLE
Uzbekistan: Characters...The Trilogy Final

### PR DESCRIPTION
**Pull request by SanzhKM**
I've added cyrillic translation to some characters, those who do not have a translation are those who you could easily find in Wikipedia or that there are no uniquely russian sources for that character.

### CODE REVIEW

**Comment by TheBrit7** [comment]
None of the leaders have portraits defined?

**Comment by SanzhKM** [comment]
> None of the leaders have portraits defined?

No, based on my tests, a generic one will be assigned, unless ya'll want to assign a specific portrait to the leaders (hence its empty); but that's not for me to decide

**Comment by ilkober** [comment]
Should be working fine, needs double checks by some other dev to make sure that portraits are shown correctly

**Comment by marijn211** [comment]
Because this is so old Ill transfer your changes onto a branch we can more easily playtest, and to avoid any issues with this being so old

**Comment by marijn211** [comment]
Advisors icons seem broken

**Pull request closed without merging**
