### PR TITLE
Add characters localisation

### PR DESCRIPTION
**Pull request by FOREVERGWC**
Add characters localisation
image
image

### CODE REVIEW

**Review by marijn211 — COMMENTED** [review]
AFG is getting some bugs fixed, to be checked after that it merged

**Comment by marijn211** [comment]
Can now be updated for Afghanistan fixes

**Comment by FOREVERGWC** [comment]
> Can now be updated for Afghanistan fixes

now it is ok, I have merged it

**Review by SpicyAlfredo — DISMISSED** [review]
Looks good. Ready?

**Comment by FOREVERGWC** [comment]
@marijn2112  Now it is updated

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
