### PR TITLE
Major Venezuela Changes

### PR DESCRIPTION
**Pull request by hurafloyd**
All these changes were made thinking to make the playthrough with Venezuela more fun. After many sessions I've found that it becomes almost impossible to beat Peru, and if you do, you dont have pops or the industry to keep up a prolonged war against the rest of South America, so the changes are made to pass that limitation.

- Modified Enforce Army Loyalty
- Modified Paramilitary Squads
- Modified Juventud Militar
- Modified Juan Gomez Legacy, to improve benefits.
- Changed German-Oil Deal to give an oil refinery.
- Added some stability to Finalize the 1935 elections
- Modified Nationalize Central Bank with a condition that the Venezuela central bank must be found.
- Modified Labour Reform with a condition that the Labour Law must exist.
- Added a slight stability increase to Address the Economic Situation.
- Adjusted the National Recovery Act to reflect improvements to the oil situation, instead of punishments.
- Adjusted Alternatives to Oil to reflect previous focus' concept.
- Adjusted Alternatives to Oil to increase building slots to 3 (2 steel mills, 1 civilian)
- Increased amounts of resources to Invest in the Mining Industry.
- Adjusted Invest in the Mining Industry to reflect previous focus' concept.
- Changed Improve Living Standards to make infraestructure instead of electronic's research.
- Added Found the Venezuelan Central Bank, adds a bit of stability and consumer goods.
- Added Labour Law which adds production, stability and research benefits.
- Removed GNB, Bolivariana or any "out of date" references.
- Modified Revive Gran Colombia to include an increase of non core population and recruitment.
- Switched Claim Trinidad to be achievable either by Gran Colombia or Visions Up North subtrees.
- Switched places with the conquer focus of Panama and Peru... Peru is too damn hard to conquer before Panama.
- Modified Gran Colombian Expansion to follow the same concept as Revive Gran Colombia (justify war goal doesnt make sense here).
- Removed GNB, Bolivariana or any "out of date" references.
- Foundation of the Guardia Nacional now gives army exp and a new idea instead of new divisions.
- Purchase Czech Weaponry has been moved up the tree, since it was kind of difficult to attain if its not done from the beginning.
- Cardona's and Angarita's subtrees are no longer mutually exclusive although their durations have been increased.
- Changed Develop Venezuelan Armour to 2x 50%.
- Modified Adapt to the Amazons, giving battle buffs to infanty in jungle.
- Added Altitude Endurance and Andinistas, focusing on mountain buffs.
- Added a Special Forces focus, which grants an idea.
- Adjusted the Modernize weaponry to 2x 50% for weapons and artillery.
- Modified VEN_oil to VEN_oil_10 to reflect changes on focuses.
- Incrased the minuses to the starting Venezuelan Oil and also stability is affected, the subsequent focuses will reduce the effect.
- Adjusted the different factors to reflect improvements and removed all traces of punishing traits to final ideas.
- Created Guardia Nacional, which grants defense and attack in core by 5% each.
- Created a Special Forces Academy idea, which grants special forces multiplier and training after getting its focus.
- Created BCV focus.
- Created Labour Law focus.
- Adjusted position of Form the DSN to belong both to Jimenez and Contreras.
- Removed DSN and Pedro Estrada effects from Crackdown and Suspend Elections.
- Military Colleges give 5 Exp each and 1 50% per doctrine. Costs 50 days.
- Privatize IFE costs 50 days.
- Increased amount of oil generated by Expand Oil Industry by 3.
- Engineering Schools give 2 uses each instead of 1.
- Explosive Factories now give 75 artillery.
- Expand Military University gives 5 Exp each and 50% each doctrine
- Foundation of the Guardia Nacional now gives less exp.
- Added BCV Idea Icon (as a place holder for now).
- Changed Suspend Elections to Suppress the Opposition. With reduced Political power but Fascism gains support, authoritarian and democracy lose support.
- Changed location of Military Colleges to be under Enforce Army Loyalty.
- Changed location of Privatize the IFE to be under Invite Foreign Students. Increased the amount of Infraestructure given.
- Adjusted Establish Paramilitary Squadrons and Form the Juventud Militar, the ideas now give mobilization speed increase although the other values have been reduced.
- Added School of the Americas, which adds counter intelligence, a slot and intelligence growth factor (icon is placeholder for now).
- Added a Claim to the Falklands and South Georgia, available only if Argentina is conquered. When the claim is accepted, the names are automatically switched to their Spanish versions (Las Malvinas and San Pedro). Also, as with Argentina, there is an opinion modifier and world tension too.
- Added to Demand Guyana change opinion modifier and world tension.
- Modified Enforced Military Loyalty to give CP.
- Added Unified Command that adds more CP and CP gain in replacement of Military Loyalty.
- Unified National Politics gives no political power now but removes recent unification idea.
- Added the colombian Field Marshal and a Ecuadorian General to Gran Colombian Army.
- Added Libertadores Legacy, improves a little bit the Gomez's legacy idea and swaps the name, requires Estado Unitario of Hispanoamerica to use.
- Added some prospect decisions
- Added Claim on the canal focus and decision involved.

My own fixes (18/05/2023)

- Fixed the Claim the Canal, forgot to add the event details (lawl).
- Fixed Andinistas which had the wrong parameters for the army.

Old R56 fixes (18/05/2023)

- Alliance with Bolivia / Plan Sureste now includes Paraguay (still thinking how to adapt these names).
- Alliance with the South / Plan Lejano Sur now includes Uruguay.
- Fixed the Trinitidad decision bug which had a restriction that wouldnt allow to capture Trinidad after getting Curaçao.

### CODE REVIEW

**Comment by hurafloyd** [comment]
I'm planning on adding a couple of starting debuff ideas with one of them being a risk of civil war, will add also an aircraft designer. I've found a couple of mistakes while testing the changes. Will commit them later.

**Comment by hurafloyd** [comment]
Still need to work on that aircraft designer and the civil war, coding the civil war might be a challenge.

**Comment by TheBrit7** [comment]
Looks like there are some good changes here. However, the indentation in the code and formatting needs improvement.

**Comment by hurafloyd** [comment]
> Looks like there are some good changes here. However, the indentation in the code and formatting needs improvement.

Still working on it :), although before I make another commit I'll try to focus on the formatting, sometimes I just place what I think and then test it before organizing the code properly. I'll upload a new update tomorrow with some fixes and changes. I had a problem with the Estado Unitario of Hispanoamerica not setting a country flag but I found a another solution to that. If I get to reflect all the ideas I have, Venezuela will have enough Focus content to last until 56 XD (and if someone does an event for Cuba's Fidel I could add more content).

**Comment by hurafloyd** [comment]
Next commits will have:

Changes, adjustments and Additions

- Now Unified Research Program requires all the previous focuses to activate.

Fixing my own errors

- Another fix to Claim the Canal, the battle wasn't starting because I set up different country tags between events (duh).
- Removed in the tooltip where it says that Estrada required Crackdown on the Communists to get.
- Fixed formatting and indentation of the code.


Old R56 fixes

- Removed a line of code in the formation of Gran Colombia that one of the possible requirements to fulfill the decision was to be a subject of Honduras (wtf?).
- Fixed a name of a General (Antnio Chalbaud to Antonio Chalbaud) wherever I found it.
- Fixed another location where a name was wrong (Delgado Chabauld to "Carlos Delgado Chalbaud".
- Adjusted some other names' grammar whenever I saw them.
- Adjusted some filters for some focuses.

**Comment by hurafloyd** [comment]
Next commits will have:

Changes, adjustments and additions

- Added a new Focus called "Architectural Enlightment" that gives a new political advisor called "Carlos Raul Villanueva", which gives construction speed increase and infrastructure construction speed increase. Can be researched only by lifting the oil curse or achieving autarky.
- Added the necessary content for the new advisor (there were no coloured pictures that I could find, if anyone can color it up, they're free to do so).
- Now Expand the Central University requires Architectural Enlightment.
- Added a new loading tip XD.
- Added the IVSS focus, which adds an idea called Instituto Venezolano de los Seguros Sociales, that adds 5% factory and dock production. I couldnt think of a better option to reflect a social security service.
- Added a Purchase French Fighters focus.

Fixing my own errors

- Now Panamanian Resource Extraction requires to have control over Panama.

Old R56 fixes

- Updated the code for Purchase Italian Bombers to include latest DLC conditions.
- Added picture of political advisor Pedro Estrada.

**Comment by hurafloyd** [comment]
Next commits will have:

Changes, adjustments and additions

- To access the material designers now their respective focuses need to be researched:

FNAV -> Explosive Factories
CAVIM -> Fund Independent Arms Industries
FVVN -> Cardona's Motorization Plan

- Changed icon for Guardia Nacional (idea).
- Changed icon for Unified Army Command (idea).
- Changed icon for Recruiting Program (idea).
- Changed icon for School of the Americas (idea).
- Changed icon for Libertadores Legacy (idea).
- Changed icon for Labour Law (idea).

Fixing my own errors

- For some reason the transfer of the Panama Canal wasnt occuring when there was a victory, I honestly have no idea what changes I did that fixed this but now it works as intended xD.

**Comment by hurafloyd** [comment]
Latest commits have:

Changes, adjustments and additions

None

Fixing my own errors

- Adjusted the code to show the owner of Falklands and South Georgia instead of exclusively England, in case someone plays Decolonized mode.
- Adjusted the decision to claim the canal to disappear if Panama is already taken, in case someone plays Decolonized mode and just takes it from the get go.
- Adjusted the decision to claim trinidad to disappear if Trinidad is already taken.

Old R56 fixes

- Added small image to Eleazar Lopez Contreras when chosen as an advisor.

**Comment by marijn211** [comment]
Please resolve conflicts and also try to see if you can fix the files wrongly being marked as completely changed, the latter is likely a prerequisite for smooth conflict resolving.

**Comment by hurafloyd** [comment]
> Please resolve conflicts and also try to see if you can fix the files wrongly being marked as completely changed, the latter is likely a prerequisite for smooth conflict resolving.

Done, I didn't understand why those conflicts happened to be honest... for a moment I thought there was a version difference between what I've commited and what you guys have but I didnt see any difference.

**Review by marijn211 — CHANGES_REQUESTED** [review]
Conflict issues, also impossible to review text differences with glitched diff (could be reviewed by installing the fork, but bugtracing any missed bugs would be impossible)

**Pull request closed without merging**
