### PR TITLE
New decision category titled 'Partisan Managment'

### PR DESCRIPTION
**Pull request by vini-44**
it adds

- new decision category for germany
- mission that spawns a dynamic modifier in states
- modifier is a large buff to resistance things
- decisions to remove said modifier

Probably needs balancing of values + the ai, let me know what needs changing.

### CODE REVIEW

**Comment by marijn211** [comment]
Ive asked people to playtest, Id like to further investigate balance

**Comment by vini-44** [comment]
anything that i should change rn?

**Comment by marijn211** [comment]
Because no one is responding, Ill playtest this again soon, then probably close PR if its too unbalanced, or accept it if not

**Comment by marijn211** [comment]
In a short war I dont notice it, in a longer one I think it might be cool to have optional micro in mountainous states, regardless of tag

**Pull request closed without merging**
