### PR TITLE
Female advisor adjustment (also Eric Blair)

### PR DESCRIPTION
**Pull request by Thinking-waffle**
Added missing gender = female to women.
Often added conditions to have limited rights or total equality.

One exception: la passionaria (ibarruri) in spain because otherwise you can't switch ideology.

Changed base game city fall events to be activated by on_action instead of being checked ever 2 days.
The two liberation of London and another one news.143 and 145 are unchanged so far.

### CODE REVIEW

**Review by marijn211 — DISMISSED** [review]
R56 ideas can be disabled, requiring them is also in general slightly questionable

**Comment by Thinking-waffle** [comment]
so ditch it all?

**Comment by marijn211** [comment]
> so ditch it all?

Maybe do the opposite and forbid the women advisors when having the opposite ideas?
Also means checking the R56 law gamerule becomes optional

**Comment by Thinking-waffle** [comment]
So not enforced patriarchy?

That was the other option discussed with Abbus.

**Comment by Thinking-waffle** [comment]
changed it all to demand not to have patriarchy instead.

**Review by marijn211 — COMMENTED** [review]
[14:57:28][no_game_date][persistent.cpp:45]: Error: "Unexpected token: gender, near line: 623" in file: "common/characters/BHU.txt" near line: 623
[14:57:28][no_game_date][persistent.cpp:45]: Error: "Unexpected token: gender, near line: 56" in file: "common/characters/CSA.txt" near line: 56
[14:57:28][no_game_date][persistent.cpp:45]: Error: "Unexpected token: gender, near line: 85" in file: "common/characters/CSA.txt" near line: 85
[14:57:28][no_game_date][persistent.cpp:45]: Error: "Unexpected token: gender, near line: 108" in file: "common/characters/CSA.txt" near line: 108
[14:57:29][no_game_date][persistent.cpp:45]: Error: "Unexpected token: gender, near line: 528" in file: "common/characters/RAJ.txt" near line: 528
[14:57:29][no_game_date][persistent.cpp:45]: Error: "Unexpected token: gender, near line: 827" in file: "common/characters/TAN.txt" near line: 827

**Comment by marijn211** [comment]
Github acted weird when I merged branch so Ill double check the diff for any issues

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
