### PR TITLE
Reboot standards

### PR DESCRIPTION
**Pull request by PordyHUN**
I followed the reboot wiki rules, and reorganized and renamed the followings:
Everything in these folders:
- gfx/interface/abilitylist
- gfx/interface/buildings
- gfx/interface/decisions
- gfx/interface/goals
- gfx/interface/ideas
- gfx/interface/technolgies
- gfx/interface/traits
All file name changed, all interface gfx file follows the new names.

### CODE REVIEW

**Comment by Greatexperiment** [comment]
Can you resolve the file conflicts on your end first? Also, why is desktop.ini in there?

**Comment by Greatexperiment** [comment]
Please clear the error log before asking for a pull. Thanks!

**Comment by PordyHUN** [comment]
Cleared error.log

**Comment by Greatexperiment** [comment]
Everything seems fine. Any further errors or issues will come up as a result of testing with the team. Amazing work!

**Pull request merged**
