### PR TITLE
update characters from old style to new style

### PR DESCRIPTION
**Pull request by FOREVERGWC**
update characters from old style to new style，and I have tested it that is ok

### CODE REVIEW

**Review by marijn211 — CHANGES_REQUESTED** [review]
The auto-indenters removal of many empty lines seems unnecessary, and probably makes the file less readable

**Comment by FOREVERGWC** [comment]
> The auto-indenters removal of many empty lines seems unnecessary, and probably makes the file less readable
This is the standard result of vscode's paradox plugin's automatic formatting, where Shift+Alt+F ensures that everyone writes the exact same format

**Comment by FOREVERGWC** [comment]
I recommend using the Paradox plugin of vscode for module creation. It automatically associates localized files to annotate key values, so many annotations are redundant and can quickly complete the code

**Comment by FOREVERGWC** [comment]
@marijn2112  ok,you are right, I have restored the deleted blank lines.Which channel should I communicate this issue on Discord?

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
