### PR TITLE
Voice lines

### PR DESCRIPTION
**Pull request by hammmurabi**
voice lines for a ton of languages sourced from kaissredux + Original Hebrew voice lines

### CODE REVIEW

**Review by TheBrit7 — CHANGES_REQUESTED** [review]
Let's not replace the vanilla voicelines, we're adding a load of storage space for a whole load of nothing. Some voicelines are also duplicates, they can be adjusted to multiple tags with the same voiceline files, check all the German Kingdoms.

In addition, we have to make sure some of the voicelines are up to quality. No offence to KX, but some of these don't sound vanilla-like, so a quality test is needed.

**Comment by hammmurabi** [comment]
> Let's not replace the vanilla voicelines, we're adding a load of storage space for a whole load of nothing. Some voicelines are also duplicates, they can be adjusted to multiple tags with the same voiceline files, check all the German Kingdoms.
> 
> In addition, we have to make sure some of the voicelines are up to quality. No offence to KX, but some of these don't sound vanilla-like, so a quality test is needed. 

I'll go over it when i get home on monday

**Comment by hammmurabi** [comment]
> Let's not replace the vanilla voicelines, we're adding a load of storage space for a whole load of nothing. Some voicelines are also duplicates, they can be adjusted to multiple tags with the same voiceline files, check all the German Kingdoms.
> 
> In addition, we have to make sure some of the voicelines are up to quality. No offence to KX, but some of these don't sound vanilla-like, so a quality test is needed.



fixed - removed the lower quality voice lines and the ones that were for nations who already had some in vanilla. Some files are "duplicate" with vanilla for example to add Italian to certain r56 releasables or German to the German kingdoms

**Review by TheBrit7 — APPROVED** [review]

**Comment by TheBrit7** [comment]
Don't merge quite yet, still got some things to do.

**Pull request merged**
