### PR TITLE
English Localization Enhancements

### PR DESCRIPTION
**Pull request by NelsonCory**
Various improvements to event text, resolving grammatical errors and spelling mistakes.

### CODE REVIEW

**Comment by BiccyThiccy** [comment]
I took a look through everything and the fixes are all improvements to me, so nicely done.

I did notice that some of the descriptions still aren't of great quality despite you fixing punctuation/spelling issues with them; if you did wish to do so, you're welcome to rewrite them and widen the scope of your changes.

**Comment by NelsonCory** [comment]
I'm happy to go through and adjust those a bit, no problem!

**Comment by NelsonCory** [comment]
@BiccyThiccy  Additional adjustments made to improve readability.

**Comment by BiccyThiccy** [comment]
I don't have merge rights unfortunately, but I've brought the existence of this Pull Request to higher-up attention, so hopefully it will make it into the next update.

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
