### PR TITLE
New Netherlands Decision Category

### PR DESCRIPTION
**Pull request by BiccyThiccy**
New Netherlands Decision Category titled 'Dutch Revanchism'

### CODE REVIEW

**Review by ilkober — DISMISSED** [review]
Looks interesting, but decisions have to be ideology-aligned/locked.
For example, I doubt that Dutch communists will integrate Flanders and then claim South Africa.

Integration decision checks could also use "has_country_flag" which is assigned after first integration.

**Comment by BiccyThiccy** [comment]
> 

That's fine, I can add some ideology-checks on the colonial ones.

**Review by ilkober — COMMENTED** [review]
Good

**Comment by marijn211** [comment]
Still seemt to show the old Benelux unifying decision for me? Or maybe I messed something up

**Comment by BiccyThiccy** [comment]
Fixed.

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
