### PR TITLE
Monarchist Germany rework

### PR DESCRIPTION
**Pull request by TheBrit7**
Isn't quite finished yet, needs death event for Ludendorff and some potential bug fixing but other than that it's good to go. Opening the PR so it can be tested and reviewed accordingly.

### CODE REVIEW

**Comment by marijn211** [comment]
FYI Im also making Germany stuff so Ill skip r56.ger.30 but I might use 31, 32 and 33

**Comment by ilkober** [comment]
Adding starting cores for German pre-unification kingdoms from the start will open a giant can of worms. Better make it a decision/ game rule.

Simple example: USSR defeats Germany, can puppet Germany and release Prussia. Complete nonsense

**Comment by TheBrit7** [comment]
Ludendorff still needs illness/death events so I'm going to need to take up those slots.

**Comment by marijn211** [comment]
> Ludendorff still needs illness/death events so I'm going to need to take up those slots.

Maybe temporarily use a very high number like 999 then I can change it back to the next free number when I merge my stuff

**Comment by TheBrit7** [comment]
Okay everything should be good to go.

**Review by ilkober — DISMISSED** [review]
With Germany being a successor state of  Prussia, there is no need for both of their cores to exist from game start.

The existence of Alsace nation should probably fall into the Occitania gamerule about cores. Instead of having a starting core, their creation can be done through a decision (similar to how Lithuania can become Memel and vice versa)

Otherwise, everything else looks very promising.

**Comment by TheBrit7** [comment]
> With Germany being a successor state of Prussia, there is no need for both of their cores to exist from game start.
> 
> The existence of Alsace nation should probably fall into the Occitania gamerule about cores. Instead of having a starting core, their creation can be done through a decision (similar to how Lithuania can become Memel and vice versa)
> 
> Otherwise, everything else looks very promising.

Did you even look at it? They're not there.

**Review by marijn211 — COMMENTED** [review]
Ill have to replace my event IDs before accepting

**Review by marijn211 — COMMENTED** [review]
Prussia cores were disabled, but theres still cores of other nations that should not be there at map start

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
