### PR TITLE
India: fix Sikkim not integrating with Princely States, Vietnam: hide irrelevant focus branches post-revolution

### PR DESCRIPTION
**Pull request by picturetheory**
Sorry for all the indenting changes. The part that matters is that india.10131 and india.4251 had their "current_state" mismatched with the events they triggered, causing Sikkim to get skipped during the integration process.

### CODE REVIEW

**Comment by picturetheory** [comment]
Vietnamese focus tree now collapses locked branches after the war for independence.

**Comment by marijn211** [comment]
All the
```
AND = {
NOT = {
a
}
NOT = {
b
}
}
```
can be replaced with
```
NOT = {
a
b
}
```
Which does the same

**Review by djberinyes — COMMENTED** [review]
Updated Vietnam.txt with cleaner code.

Edit: This is picturetheory, my GitHub deskto client switched accounts on me.

**Review by marijn211 — CHANGES_REQUESTED** [review]
Im not sure when these flags get added, but when none are added, the focus tree is broken, e.g. when Asia starts decolonized

**Comment by marijn211** [comment]
Will close for now but feel free to reopen if changed, Im not very familiar with India nor Vietnam content so I cant finish this myself

**Pull request closed without merging**
