### PR TITLE
Brit october 1

### PR DESCRIPTION
**Pull request by TheBrit7**

### CODE REVIEW

**Comment by marijn2112** [comment]
Error loading country flag overlay: gfx/flags/medium/PAL_democratic.tga : Unexpected texture dimensions

**Review by marijn211 — DISMISSED** [review]
Check error log

**Comment by TheBrit7** [comment]
> Check error log

What about it? It was okay last time I checked.

**Comment by marijn211** [comment]
> > Check error log
> 
> What about it? It was okay last time I checked.

Theres several things, the one I recall is the flags throwing errors, but there was other stuff

**Comment by marijn2112** [comment]
[16:04:44][flagtextureatlas.cpp:203]: Error loading country flag overlay: gfx/flags/medium/PAL_ALL_PALESTINE_neutrality.tga : Unexpected texture dimensions

**Comment by marijn211** [comment]
Please fix medium/PAL_unified or whatever its called, an error pops up in country selection error log

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
