### PR TITLE
Waffle return

### PR DESCRIPTION
**Pull request by Thinking-waffle**

### CODE REVIEW

**Comment by Greatexperiment** [comment]
[09:06:29][pdx_localize.cpp:1152]: Illegal break character (utf32=61) at line 10 and column 38 in localisation/replace/r56_startup_l_english.yml
[09:06:31][pdx_localize.cpp:1152]: Illegal break character (utf32=61) at line 10 and column 38 in localisation/replace/r56_startup_l_english.yml
[09:08:29][persistent.cpp:42]: Error: "Unexpected token: targeted_modifier, near line: 69
" in file: "common/decisions/RUT.txt" near line: 69
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country SUR : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country SEN : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country SLE : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country SOM : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country TNZ : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country TNA : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country UGA : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country VLA : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country WAF : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country WHY : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country WLL : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:58][flagtextureatlas.cpp:465]: Error loading flag for country WSH : Ideology democratic : Path gfx/flags/medium/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country AHV : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country BAH : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country BLZ : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country BOS : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country BRI : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country CAR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country CAT : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country CYP : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country DJB : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country DNZ : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country DON : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country DOU : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country EFR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country EQG : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country ERI : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country EUS : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country FAK : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country FRI : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country G01 : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GAB : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GAM : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GHA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GRL : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GUN : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GBR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country JAM : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country KUR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MAD : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MAU : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MCD : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MLI : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MOR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country NGR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country NIG : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country NMB : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country PGR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country PUE : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country QBC : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country RGR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country RUT : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SCA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SDN : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SUR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SEN : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SLE : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SOM : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country TNZ : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country TNA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country UGA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country VLA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country WAF : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country WHY : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country WLL : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country WSH : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country AHV : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country BAH : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country BLZ : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country BOS : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country BRI : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country CAR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country CAT : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country CYP : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country DJB : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country DNZ : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country DON : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country DOU : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country EFR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country EQG : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country ERI : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country EUS : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country FAK : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country FRI : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country G01 : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GAB : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GAM : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GHA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GRL : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GUN : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country GBR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country JAM : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country KUR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MAD : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MAU : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MCD : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MLI : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country MOR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country NGR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country NIG : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country NMB : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country PGR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country PUE : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country QBC : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country RGR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country RUT : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SCA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SDN : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SUR : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SEN : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SLE : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country SOM : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country TNZ : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country TNA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country UGA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country VLA : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country WAF : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country WHY : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country WLL : Ideology democratic : Path gfx/flags/small/ : File not found
[09:08:59][flagtextureatlas.cpp:465]: Error loading flag for country WSH : Ideology democratic : Path gfx/flags/small/ : File not found

**Comment by Thinking-waffle** [comment]
wait those flag errors are still there. ugh

**Comment by Greatexperiment** [comment]
[09:40:17][persistent.cpp:42]: Error: "Unexpected token: targeted_modifier, near line: 69
" in file: "common/decisions/RUT.txt" near line: 69

**Comment by Greatexperiment** [comment]
Looks good. Please update the notes.

**Pull request merged**
