### PR TITLE
final israel rework before i get conscripted

### PR DESCRIPTION
**Pull request by hammmurabi**
i love the israeli air force <3

### CODE REVIEW

**Comment by hammmurabi** [comment]
Opened PR as i am going on vacation soon - only GFX missing at this point

**Review by TheycallmeBrick — COMMENTED** [review]
Having played the nation a number of times on a number of paths as a tester, I can attest that this focus is indeed playable and ready to launch following a few additional gfx being added.

**Review by marijn211 — CHANGES_REQUESTED** [review]
Check error log

**Comment by hammmurabi** [comment]
> Check error log



fixed

**Comment by marijn2112** [comment]
ISR_avraham_tehomi does not have a valid icon

**Review by marijn211 — APPROVED** [review]

**Pull request merged**
