### PR TITLE
Delete duplicate Honduras file

### PR DESCRIPTION
**Pull request by Zurich899**
There's two copies of the Honduras national focus file in Github, and it looks like the one that isn't capitalized is the more recent one. Can we delete this one to reduce confusion?

### CODE REVIEW

**Comment by Greatexperiment** [comment]
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_banana_boats (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_eliminate_competition (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_corporate_expansion (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_corporate_consolidation (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_liberate_central (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_real_gran_colombia (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_real_gran_colombia (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_real_gran_colombia (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_fullcaribfed (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_fullcaribfed (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_fullcaribfed (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_fullcaribfed (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_fullcaribfed (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_fullcaribfed (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_libbolivia (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_liblaplata (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_liblaplata (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_liblaplata (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_restoration_wars (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_reclaim_spain (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_reclaim_america (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_liberate_guatemala (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_reclaim_guatemala (Error in trigger:has_completed_focus)
[17:31:15][triggerimplementation.cpp:3913]: Invalid focus scripted in trigger. has_completed_focus = HON_liberate_panama (Error in trigger:has_completed_focus)

**Comment by Zurich899** [comment]
I just loaded up the beta with the Honduras.txt file deleted and checked the error log. My error log was empty except for a few missing textures. I'm not sure how you got that list of errors, especially when the version of R56 that I downloaded from the workshop only has the lower-case national focus file.

**Comment by Greatexperiment** [comment]
The lower case file doesn't exist in the repository, so when the upper case one is deleted it causes those errors. I am unsure why you have or are able to see two versions.

**Comment by Zurich899** [comment]
That's really odd, especially since Pordy mentioned both of them in a pull request.  The links to both of them are below. I also tried logging out, and can still see it. 

https://github.com/deliciousmods/1956_beta/blob/Beta-Edits/common/national_focus/Honduras.txt
https://github.com/deliciousmods/1956_beta/blob/Beta-Edits/common/national_focus/honduras.txt

**Comment by Greatexperiment** [comment]
I manually removed the file so this pull request is no longer needed.

**Comment by Zurich899** [comment]
Perfect, it now looks good on my end. Thank you for looking into this and I'm sorry for the confusion

**Pull request closed without merging**
