### PR TITLE
Chile Changes

### PR DESCRIPTION
**Pull request by AlanBF1992**
Changed Chilean Events, Decisions and Focuses to include Hanga Roa and other Isles.
Changed their Communist Party Leader to the correct one.
Fixed communist annexation event to properly fire for subjects

### CODE REVIEW

**Review by marijn211 — DISMISSED** [review]
I can see some typo ` symbols in the diff, see error log

**Comment by AlanBF1992** [comment]
Fixed. I'm checking other things like advisors, decisions and states for the different paths too

**Review by hammmurabi — CHANGES_REQUESTED** [review]
[20:10:14][no_game_date][pdx_audiomusic_sdl.cpp:77]: For best performance and quality music files should be in 44.1kHz (Sangena Mama)

[20:10:15][no_game_date][pdx_audiomusic_sdl.cpp:77]: For best performance and quality music files should be in 44.1kHz (Kamome)

[20:10:17][no_game_date][pdx_audiomusic_sdl.cpp:77]: For best performance and quality music files should be in 44.1kHz (Antofagasta Dormida)

[20:10:17][no_game_date][pdx_audiomusic_sdl.cpp:77]: For best performance and quality music files should be in 44.1kHz (El Relojito)

[20:10:17][no_game_date][pdx_audiomusic_sdl.cpp:77]: For best performance and quality music files should be in 44.1kHz (Valparaiso)

[20:10:19][no_game_date][effect.cpp:432]: Invalid effect 'modifier' in common/decisions/CHL_decisions.txt line : 9382

[20:10:19][no_game_date][effect.cpp:432]: Invalid effect 'remove_effect' in common/decisions/CHL_decisions.txt line : 9385

[20:10:19][no_game_date][effect.cpp:344]: Error: "Unknown effect-type: modifier, near line: 9382

Unknown effect-type: remove_effect, near line: 9385" in file: "common/decisions/CHL_decisions.txt" near line: 9388

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_the_kingdom_of_mexico, near line: 9400" in file: "common/decisions/CHL_decisions.txt" near line: 9466

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_french_guyana, near line: 9469" in file: "common/decisions/CHL_decisions.txt" near line: 9547

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_st_pierre, near line: 9550" in file: "common/decisions/CHL_decisions.txt" near line: 9628

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_french_caribbean, near line: 9631" in file: "common/decisions/CHL_decisions.txt" near line: 9709

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_corsica, near line: 9712" in file: "common/decisions/CHL_decisions.txt" near line: 9790

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_northern_france, near line: 9793" in file: "common/decisions/CHL_decisions.txt" near line: 9880

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_southern_france, near line: 9883" in file: "common/decisions/CHL_decisions.txt" near line: 9972

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_rio_grande_do_sul, near line: 9975" in file: "common/decisions/CHL_decisions.txt" near line: 10101

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_quebec, near line: 10104" in file: "common/decisions/CHL_decisions.txt" near line: 10183

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_araucania_establish_inca_kingdom, near line: 10186" in file: "common/decisions/CHL_decisions.txt" near line: 10502

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_integrate_the_south_atlantic_islands_araucania, near line: 10505" in file: "common/decisions/CHL_decisions.txt" near line: 10628

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_araucania_establish_a_guianan_government, near line: 10631" in file: "common/decisions/CHL_decisions.txt" near line: 10851

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_araucania_establish_a_hispaniolan_kingdom, near line: 10854" in file: "common/decisions/CHL_decisions.txt" near line: 11129

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_bolster_revolutionaries_americas, near line: 11137" in file: "common/decisions/CHL_decisions.txt" near line: 11205

[20:10:19][no_game_date][persistent.cpp:45]: Error: "Unexpected token: CHL_initiate_a_revolution, near line: 11208" in file: "common/decisions/CHL_decisions.txt" near line: 11358

[20:10:24][no_game_date][effectimplementation.cpp:13905]: Invalid Decision ID for unlock_decision_tooltip CHL_integrate_rio_grande_do_sul

[20:10:24][no_game_date][effectimplementation.cpp:13905]: Invalid Decision ID for unlock_decision_tooltip CHL_integrate_the_kingdom_of_mexico

[20:10:24][no_game_date][effectimplementation.cpp:13905]: Invalid Decision ID for unlock_decision_tooltip CHL_integrate_quebec

**Comment by AlanBF1992** [comment]
Fixed. I have to stop playing things while coding.

**Review by hammmurabi — APPROVED** [review]
Errors fixed and seems to work ok

**Pull request merged**
