### PR TITLE
Dodecaneso

### PR DESCRIPTION
**Pull request by Altitud49**
Fixed some Côte d'Ivoire spellings and added an Italian name for Dodecanese so that ids just do not pop randomly when hovering over Rhodes.

### CODE REVIEW

**Comment by marijn211** [comment]
I think you forgot to rename the Dodecanese for the Italian version

**Comment by Altitud49** [comment]
I also recolored Slovenia and Macedonia

**Comment by marijn211** [comment]
It seems like youre missing a `"` behind your extra loc line for Monaco (it seems this also applies to loc of the preceding states)
I dont see why we would need to change those country colors to the base game ones, but theyre not terrible either

**Comment by Altitud49** [comment]
It seems that the quotation marks were forgotten during the addition of the Microstates

**Comment by Altitud49** [comment]
The Côte d'Ivoire fix is no longer needed as it has already been fixed in the new countries localisation file, speaking of the new countries localisation, I sorted them in alphabetical order so it is easier to find what we need without ctrl+f, for example, adding the missing countries such as Green Ukraine

**Comment by Altitud49** [comment]
Ok so apparently Mauritania has not the same tag in he first one than in the other
I guess this is heavily in the works I didn't add Green Ukraine nor Hyderabad I just classified it alphabetically revert my changes if I shouldn't have.
I'll just wait for the next update to clean this all up

**Comment by TheBrit7** [comment]
Do that whenever you're ready to.

**Comment by Altitud49** [comment]
Ok I was bored just fixed the file, I figure we can now delete the original "r56_countries.yml"

**Comment by Altitud49** [comment]
Was there an error in my code ? Did I do something wrong ? (please just tell me I do not wan't to keep making the same mistakes over and over again)

**Comment by Altitud49** [comment]
Silly me it didn't even get reviewed...

**Pull request closed without merging**
