### PR TITLE
Localisation fixes

### PR DESCRIPTION
**Pull request by Altitud49**
Plz review before closing 😢  
Recolored Slovenia and Macedonia to their basegame color.
Fixed a typo in Monaco's "Prestigious Reputation"
Sorted alphabetically the new countries.yml, added the missing countries to it, then deleted the original r56_countries.yml as it's now deprecated, and its info migrated.

### CODE REVIEW

**Comment by TheBrit7** [comment]
You deleted the country name folder and added a lot to the base game one. Also what did you change with the state names? You seem to of have spaced them out unnecessarily and I am unsure if it's formatting would work correctly.

**Comment by Altitud49** [comment]
Some quotation marks in the state names were forgotten, I added them in and added an Italian name for the Dodecanese, as for the unnecessary spaces they were already there when I got here.

If it seems I added a lot to the base game "countries.yml", I just sorted them out alphabetically and added around ten localizations of countries that wouldn't show up, for exemple if you balkanized the Soviet Union, Green Ukraine would show up as nothing, Hyderabad's and Andorra's weren't showing up corrctly either. It didn't matter if the localisations were in the RT56 one, the game wouldn't pick them up with the excuse that the original still existed. By moving the missing content and deleting "r56_countries.yml" (which doesn't do anything now that we moved the missing content), the correct names appear on the map.

**Comment by TheBrit7** [comment]
This PR isn't going to be accepted at the moment. There is a separate file for our names for a reason, pleas keep it that way.

**Comment by marijn211** [comment]
Because forks are more difficult to play-test, Ill probably copy any non-ported state localization fixes onto a different PR

**Comment by Altitud49** [comment]
Oh okay

**Pull request closed without merging**
